---
# enable this role when no PermitRootLogin and sudo user has public key in authorized_keys
# specify that sudo user in roles\allowrootaccesswithpublickey\vars\main.yml ansible_ssh_user: <sudo user>
# ====================
# - hosts: k3s_cluster
#   become: true
#   roles:
#     - role: allowrootaccesswithpublickey
# ====================

- hosts: proxmox
  gather_facts: true
  become: yes
  roles:
    - role: proxmox_lxc
      when: proxmox_lxc_configure

- hosts: k3s_cluster
  gather_facts: yes
  roles:
    - role: lxc
      become: true
      when: proxmox_lxc_configure
    - role: prereq
      become: true
    - role: download
      become: true
    - role: raspberrypi
      become: true

- hosts: master
  roles:
    - role: k3s/master
      become: true

- hosts: node
  roles:
    - role: k3s/node
      become: true

- hosts: master
  roles:
    - role: k3s/post
      become: true

- hosts: master[0]
  become: true
  roles:
    - role: helm

- hosts: master[0]
  become: true
  roles:
    - role: rancher