- name: Create rancher config directory on first master
  file:
    path: /tmp/rancher
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy rancher loadbalancer service to first master
  template:
    src: "lb-svc.yml.j2"
    dest: /tmp/rancher/lb-svc.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: add rancher helm repo
  command:
    cmd: "helm repo add rancher-stable https://releases.rancher.com/server-charts/stable"
  changed_when: true

- name: update helm repo
  command:
    cmd: "helm repo update"
  changed_when: true

- name: wait for k3s API server VIP {{ apiserver_endpoint }} to be available
  wait_for:
    host: "{{ apiserver_endpoint }}"
    port: 6443
    delay: 10

- name: create the cattle-system namespace for rancher
  command:
    cmd: kubectl create namespace cattle-system
  changed_when: true

- name: deploy rancher with dns name {{ rancher_dns_name }}
  command:
    cmd: helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname="{{ rancher_dns_name }}" --set bootstrapPassword="{{ rancher_bootstrap_password }}" --set ingress.enabled=false --set ingress.tls.source=secret
  changed_when: true

- name: apply rancher LoadBalancer IP Service
  command:
    cmd: kubectl apply -f /tmp/rancher/lb-svc.yml --namespace=cattle-system
  changed_when: true

- name: Clean up rancher tmp dir
  file:
    path: /tmp/rancher/
    state: absent